### ISSUE TITLE
New publication type in SE - Preprint

### ISSUE THREAD

**Issue by mrdsaunders** [bodleian/ora_data_model#191]
**New SE output type 'Preprint'**
- Defined in SE as a submitted version of a journal article that is published in its own right prior to peer review/publication, usually with a separate DOI.
- Will be implemented with the v6.x PROD upgrade.
- Will be crosswalk to ORA as 'Internet Publication'. 
- Preprints [in SE] will be kept as separate objects and not amended to 'journal article' on publication, or merged with the published version. 
- The published versions [of preprint] should have a different DOI to any later published version [journal article] so [journal article record] should not harvest to the preprint record.
- Our advice to users will be not to merge with published journal article, but to hide or unclaim the preprint if they are not wanted on their record.
- There is a relationship type 'is preprint of' which we will advise people to use (create new link), although we are of course not sure yet how much people will make use of this

**Comment by mrdsaunders** [comment]
This has been discussed via Teams and agreed to proceed.
Simple test for deposit and fetch on deposit in SUPP passed.

**Comment by jjpartridge** [comment]
@mrdsaunders this looks good to me. We may have to assess some aspects further along as depositors start using the new item type, and make sure that workflows are adjusted accordingly.

Thanks.

**Comment by mrdsaunders** [comment]
Implemented with v6, no issues reported, so closing.
