### ISSUE TITLE
Depositors not being mapped to Authors in QA

### ISSUE THREAD

**Issue by tomwrobel** [bodleian/ora_data_model#194]
The deposit crosswalk [has a section which maps depositors to authors, starting at line 900](https://github.com/bodleian/ora_data_model/blob/e1b3f66416eeb7ab2ac4a487d7cc2e4a54e20fd1/elements_xwalks/maps/hyrax-XwalkOut-map.xml#L900)

The mapping relies on a mapping between Oxris User ids: if a contributor with that Oxris User id is found, then the depositor role is added to that contributor. If not, a second contributor is created.

The relevant test is:

```
            <xwalk:condition argument-field="string(/api:push-object/api:object/api:view/api:field[@name = 'authors' or @name = 'editors']/api:people/api:person/api:links/api:link[@type = 'elements/user' and @id = string(/api:push-object/api:push-supplementary-info/api:deposit-info/api:depositor/@id)]/@id)" operator="has-value" select-using="xpath" />
```

On QA, this test is failing (e.g. for 1212561), and as a result authors who are also depositors are having two contributor records created for them. This is not ideal.

Is this a case of a data feed not being hooked up, or will we see this issue increasingly on PRD?

**Comment by tomwrobel** [comment]
Looking at the crosswalk input, the user ID appears to be the same. I don’t know why it’s failing, sorry

**Comment by tomwrobel** [comment]
The test looks for the id in `/api:push-object/api:push-supplementary-info/api:deposit-info/api:depositor/@id`, and it should be there. I'll have to leave this one to you, at least initially

**Comment by mrdsaunders** [comment]
Hi Tom.., sorry to be dim but I am unable to replocate this in QA using the test crosswalks screen. If I impersonate you and deposit (1212564) I see both roles assigned to you:
```
<mods:role>
    <mods:extension>
        <ora:role_order>1</ora:role_order>
    </mods:extension>
    <mods:roleTerm type="text">Author</mods:roleTerm>
 </mods:role>
 <mods:role>
    <mods:extension>
        <ora:role_order>1</ora:role_order>
    </mods:extension>
    <mods:roleTerm type="text">Depositor</mods:roleTerm>
 </mods:role>
```
Are you seeing different in ORA?

**Comment by tomwrobel** [comment]
I uploaded the most recent crosswalk after creating this ticket. I think that may have fixed it

**Comment by tomwrobel** [comment]
I can confirm that the crosswalk for 1212561 is now fixed. The issue was that the newest crosswalks weren't uploaded. Thank you! Closing
